=== fredicinho/HSLU-XML-HS19/schemaEventDB.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="events">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="event" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="eventID">
			<xs:selector xpath="event"/>
			<xs:field xpath="@id"/>
		</xs:unique>
	</xs:element>
	<xs:element name="event">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="xs:string"/>
				<xs:element name="dauerInTagen" type="xs:positiveInteger"/>
				<xs:element name="startdatum" type="xs:date"/>
				<xs:element name="beschreibung" type="xs:string"/>
				<xs:element ref="handicap"/>
				<xs:element name="anzahlMöglicheTeilnehmer" type="xs:positiveInteger"/>
				<xs:element name="anzahlTeilnehmer" type="xs:nonNegativeInteger"/>
				<!--Ist findetStatt notwendig? - aw -->
				<xs:element name="findetStatt" type="xs:boolean"/>
				<xs:element ref="teilnehmerListe"/>
			</xs:sequence>
			<xs:attribute name="name" type="eventType" use="required"/>
			<xs:attribute name="id" type="xs:positiveInteger"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="teilnehmerListe">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="teilnehmer" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="teilnehmer">
		<xs:complexType>
			<xs:all minOccurs="0">
				<xs:element name="vorname" type="xs:string"/>
				<xs:element name="nachname" type="xs:string"/>
				<xs:element name="geschlecht" type="gender"/>
				<xs:element name="adresse" type="xs:string"/>
				<xs:element name="stadt" type="xs:string"/>
				<xs:element name="telefonnummer" type="xs:positiveInteger"/>
				<xs:element name="geburtstag" type="xs:date"/>
				<xs:element ref="behinderung"/>
				<xs:element name="einzelzimmer" type="xs:boolean"/>
				<xs:element name="spezielles" type="xs:string"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="handicap">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="behinderung" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="behinderung">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Geistige Behinderung"/>
				<xs:enumeration value="Höhrbehinderung"/>
				<xs:enumeration value="Körperbehinderung"/>
				<xs:enumeration value="Psychische Behinderung"/>
				<xs:enumeration value="Sehbehinderung"/>
				<xs:enumeration value="Keine Behinderung"/>
				<xs:enumeration value="Diverse Behinderungen"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:simpleType name="eventType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Fussball"/>
			<xs:enumeration value="Basketball"/>
			<xs:enumeration value="Schwimmen"/>
			<xs:enumeration value="Klettern"/>
			<xs:enumeration value="Ski und Snowboard"/>
			<xs:enumeration value="Schnitzeljagd"/>
			<xs:enumeration value="Wandern"/>
			<xs:enumeration value="Fahrrad"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="gender">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Weiblich"/>
			<xs:enumeration value="Männlich"/>
			<xs:enumeration value="Anderes"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== fredicinho/HSLU-XML-HS19/Datenbank.xml
<?xml version="1.0" encoding="UTF-8"?>
<events xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemaEventDB.xsd">
      <event name="Fussball" id="1">
            <title>Fussballturnier</title>
            <dauerInTagen>3</dauerInTagen>
            <startdatum>2020-03-16</startdatum>
            <beschreibung>Dreitägiges Fussballturnier mit verschiedenen Disziplinen wie Torwandschiessen, Jonglieren sowie Teamspiele!</beschreibung>
            <handicap>
                  <behinderung>Psychische Behinderung</behinderung>
            </handicap>
            <anzahlMöglicheTeilnehmer>20</anzahlMöglicheTeilnehmer>
            <anzahlTeilnehmer>14</anzahlTeilnehmer>
            <findetStatt>true</findetStatt>
            <teilnehmerListe>
                  <teilnehmer>
                        <vorname>Hans</vorname>
                        <nachname>Michel</nachname>
                        <geschlecht>Anderes</geschlecht>
                        <adresse>Strasse 1</adresse>
                        <stadt>Burgdorf</stadt>
                        <telefonnummer>0834875937374</telefonnummer>
                        <geburtstag>1995-05-02</geburtstag>
                        <behinderung>Psychische Behinderung</behinderung>
                        <einzelzimmer>true</einzelzimmer>
                        <spezielles/>
                  </teilnehmer>
                  <teilnehmer>
                        <vorname>Hanna</vorname>
                        <nachname>Capital</nachname>
                        <geschlecht>Weiblich</geschlecht>
                        <adresse>Strasse 1</adresse>
                        <stadt>Burgdorf</stadt>
                        <telefonnummer>0834875937374</telefonnummer>
                        <geburtstag>1995-05-02</geburtstag>
                        <behinderung>Psychische Behinderung</behinderung>
                        <einzelzimmer>false</einzelzimmer>
                        <spezielles/>
                  </teilnehmer>
                  <teilnehmer>
                        <vorname>Frederico</vorname>
                        <nachname>Fischer</nachname>
                        <geschlecht>Weiblich</geschlecht>
                        <adresse>Elfenweg, 7</adresse>
                        <stadt>Burgdorf</stadt>
                        <telefonnummer>+41765205522</telefonnummer>
                        <geburtstag>2020-02-14</geburtstag>
                        <behinderung>Geistige Behinderung</behinderung>
                        <einzelzimmer>false</einzelzimmer>
                        <spezielles>asdf</spezielles>
                  </teilnehmer>
                  <teilnehmer>
                        <vorname>Frederico</vorname>
                        <nachname>Fischer</nachname>
                        <geschlecht>Weiblich</geschlecht>
                        <adresse>Elfenweg, 7</adresse>
                        <stadt>Burgdorf</stadt>
                        <telefonnummer>+41765205522</telefonnummer>
                        <geburtstag>2020-02-14</geburtstag>
                        <behinderung>Geistige Behinderung</behinderung>
                        <einzelzimmer>false</einzelzimmer>
                        <spezielles>asdf</spezielles>
                  </teilnehmer>
                  <teilnehmer>
                        <vorname>Frederico</vorname>
                        <nachname>Fischer</nachname>
                        <geschlecht>Männlich</geschlecht>
                        <adresse>Elfenweg, 7</adresse>
                        <stadt>Burgdorf</stadt>
                        <telefonnummer>+41765205522</telefonnummer>
                        <geburtstag>2020-02-21</geburtstag>
                        <behinderung>Keine Behinderung</behinderung>
                        <einzelzimmer>true</einzelzimmer>
                        <spezielles>asdf</spezielles>
                  </teilnehmer>
                  <teilnehmer>
                        <vorname>Frederico</vorname>
                        <nachname>Fischer</nachname>
                        <geschlecht>Anderes</geschlecht>
                        <adresse>Elfenweg, 7</adresse>
                        <stadt>Burgdorf</stadt>
                        <telefonnummer>+41765205522</telefonnummer>
                        <geburtstag>2020-02-22</geburtstag>
                        <behinderung>Höhrbehinderung</behinderung>
                        <einzelzimmer>true</einzelzimmer>
                        <spezielles>asd</spezielles>
                  </teilnehmer>
                  <teilnehmer>
                        <vorname>Frederico</vorname>
                        <nachname>Fischer</nachname>
                        <geschlecht>Anderes</geschlecht>
                        <adresse>Elfenweg, 7</adresse>
                        <stadt>Burgdorf</stadt>
                        <telefonnummer>+41765205522</telefonnummer>
                        <geburtstag>2020-02-22</geburtstag>
                        <behinderung>Höhrbehinderung</behinderung>
                        <einzelzimmer>true</einzelzimmer>
                        <spezielles>asd</spezielles>
                  </teilnehmer>
                  <teilnehmer>
                        <vorname>Frederico</vorname>
                        <nachname>Fischer</nachname>
                        <geschlecht>Anderes</geschlecht>
                        <adresse>Elfenweg, 7</adresse>
                        <stadt>Burgdorf</stadt>
                        <telefonnummer>+41765205522</telefonnummer>
                        <geburtstag>2020-02-22</geburtstag>
                        <behinderung>Höhrbehinderung</behinderung>
                        <einzelzimmer>true</einzelzimmer>
                        <spezielles>asd</spezielles>
                  </teilnehmer>
                  <teilnehmer>
                        <vorname>Frederico</vorname>
                        <nachname>Fischer</nachname>
                        <geschlecht>Anderes</geschlecht>
                        <adresse>Elfenweg, 7</adresse>
                        <stadt>Burgdorf</stadt>
                        <telefonnummer>+41765205522</telefonnummer>
                        <geburtstag>2020-02-22</geburtstag>
                        <behinderung>Höhrbehinderung</behinderung>
                        <einzelzimmer>true</einzelzimmer>
                        <spezielles>asd</spezielles>
                  </teilnehmer>
                  <teilnehmer>
                        <vorname>Frederico</vorname>
                        <nachname>Fischer</nachname>
                        <geschlecht>Weiblich</geschlecht>
                        <adresse>Elfenweg, 7</adresse>
                        <stadt>Burgdorf</stadt>
                        <telefonnummer>+41765205522</telefonnummer>
                        <geburtstag>2020-02-22</geburtstag>
                        <behinderung>Höhrbehinderung</behinderung>
                        <einzelzimmer>false</einzelzimmer>
                        <spezielles>asdf</spezielles>
                  </teilnehmer>
                  <teilnehmer>
                        <vorname>Frederico</vorname>
                        <nachname>Fischer</nachname>
                        <geschlecht>Weiblich</geschlecht>
                        <adresse>Elfenweg, 7</adresse>
                        <stadt>Burgdorf</stadt>
                        <telefonnummer>+41765205522</telefonnummer>
                        <geburtstag>2020-02-22</geburtstag>
                        <behinderung>Höhrbehinderung</behinderung>
                        <einzelzimmer>false</einzelzimmer>
                        <spezielles>asdf</spezielles>
                  </teilnehmer>
                  <teilnehmer>
                        <vorname>Frederico</vorname>
                        <nachname>Fischer</nachname>
                        <geschlecht>Weiblich</geschlecht>
                        <adresse>Elfenweg, 7</adresse>
                        <stadt>Burgdorf</stadt>
                        <telefonnummer>+41765205522</telefonnummer>
                        <geburtstag>2020-02-22</geburtstag>
                        <behinderung>Höhrbehinderung</behinderung>
                        <einzelzimmer>false</einzelzimmer>
                        <spezielles>asdf</spezielles>
                  </teilnehmer>
                  <teilnehmer>
                        <vorname>Frederico</vorname>
                        <nachname>Fischer</nachname>
                        <geschlecht>Weiblich</geschlecht>
                        <adresse>Elfenweg, 7</adresse>
                        <stadt>Burgdorf</stadt>
                        <telefonnummer>+41765205522</telefonnummer>
                        <geburtstag>2020-02-22</geburtstag>
                        <behinderung>Höhrbehinderung</behinderung>
                        <einzelzimmer>false</einzelzimmer>
                        <spezielles>asdf</spezielles>
                  </teilnehmer>
                  <teilnehmer>
                        <vorname>Nico</vorname>
                        <nachname>Iseli</nachname>
                        <geschlecht>Weiblich</geschlecht>
                        <adresse>Strasse</adresse>
                        <stadt>Luzern</stadt>
                        <telefonnummer>234234</telefonnummer>
                        <geburtstag>2020-02-28</geburtstag>
                        <behinderung>Psychische Behinderung</behinderung>
                        <einzelzimmer>true</einzelzimmer>
                        <spezielles/>
                  </teilnehmer>
            </teilnehmerListe>
      </event>



      <event name="Klettern" id="2">
            <title>Klettern in den Bergen</title>
            <dauerInTagen>4</dauerInTagen>
            <startdatum>2020-03-23</startdatum>
